name: Build Eaglercraft Version and ship via Releases

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v4
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '21'
            - name: Build
              run: |
                  echo "Building EPK..."
                  java -jar "desktopRuntime/CompileEPK.jar" "desktopRuntime/resources" "javascript/assets.epk"
                  echo "Finished Building EPK, continuing with JS"
                  chmod +x gradlew
                  ./gradlew generateJavascript --watch-fs --info
                  echo "Done building all scripts"
            - name: Generate example
              run: |
                java -cp "desktopRuntime/MakeOfflineDownload.jar:desktopRuntime/CompileEPK.jar" net.lax1dude.eaglercraft.v1_8.buildtools.workspace.MakeOfflineDownload "javascript/OfflineDownloadTemplate.txt" "javascript/classes.js" "javascript/assets.epk" "javascript/EaglercraftX_1.8_Offline_en_US.html" "javascript/EaglercraftX_1.8_Offline_International.html" "javascript/lang"
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist-without-markdown
                path: |
                    dist